version: 2.1

orbs:
  slack: circleci/slack@4.13.2

base_container: &base_container
  image: buildpack-deps:bookworm
  
build_containers: &build_containers
  docker:
    - <<: *base_container

test_containers: &test_containers
  docker:
    - <<: *base_container

slack_context: &slack_context
  context:
    - slack

only_main: &only_main
  filters:
    branches:
      only:
        - main

only_dependabot: &only_dependabot
  filters:
    branches:
      only:
        - /^dependabot.*/

only_main_and_dependabot: &only_main_and_dependabot
  filters:
    branches:
      only:
        - main
        - /^dependabot.*/

commands:
  notify:
    steps:
      - when:
          condition:
            matches:
              pattern: "^dependabot.*"
              value: << pipeline.git.branch >>
          steps:
            - slack/notify:
                event: fail
                channel: builds-dependabot
                template: SLACK_FAILURE_NOTIFICATION
            - slack/notify:
                event: pass
                channel: builds-dependabot
                template: SLACK_SUCCESS_NOTIFICATION
      - when:
          condition:
            matches:
              pattern: "^(?!dependabot).*"
              value: << pipeline.git.branch >>
          steps:
            - slack/notify:
                event: fail
                channel: dev
                template: SLACK_FAILURE_NOTIFICATION
            - slack/notify:
                event: pass
                channel: builds
                template: SLACK_SUCCESS_NOTIFICATION

  configure_docker:
    steps:
      - run: ./scripts/ci/common/install-docker.sh
      - setup_remote_docker:
          docker_layer_caching: true

  restore_ruby_dependency_cache:
    steps:
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-v2-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-v2-

  restore_dependency_caches:
    steps:
      - restore_ruby_dependency_cache

  save_ruby_dependency_cache:
    steps:
      - save_cache:
          key: gem-cache-{{ arch }}-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.bundle
            - ~/.asdf/installs/ruby/3.1.1/lib/ruby/gems

  save_dependency_caches:
    steps:
      - save_ruby_dependency_cache


  configure_build_tools:
    steps:
      - run: ./scripts/ci/common/install-slack-deps.sh
      - restore_cache:
          keys:
            - asdf-dependencies-{{ arch }}-v3-{{ checksum ".tool-versions" }}
            - asdf-dependencies-{{ arch }}-v3-
      - run: ./scripts/ci/common/install-asdf.sh
      - run: ./scripts/ci/common/configure-asdf.sh
      - run: ./scripts/ci/common/install-asdf-dependencies.sh
      - run: ./scripts/ci/common/configure-nodejs.sh
      - run: ./scripts/ci/common/configure-poetry.sh
      - save_cache:
          key: asdf-dependencies-{{ arch }}-v3-{{ checksum ".tool-versions" }}
          paths:
            - ~/.asdf

  configure_secrets_tools:
    steps:
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/configure-git.sh

  configure_release_tools:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:wJ0UQ3rhCtbxqcpCC7qYgVTkhdKZEuUAAg1hy4pOf8U"
      - run: ./scripts/ci/common/configure-git.sh

jobs:
  build:
    <<: *build_containers
    steps:
      - checkout
      - configure_build_tools
      - restore_dependency_caches
      - configure_secrets_tools
      - run: ./scripts/ci/steps/build.sh
      - store_artifacts:
          path: dist
      - save_dependency_caches
      - notify

  test:
    <<: *test_containers
    working_directory: ~/source
    steps:
      - checkout
      - configure_build_tools
      - restore_dependency_caches
      - configure_secrets_tools
      - run: ./scripts/ci/steps/test.sh
      - save_dependency_caches
      - notify

  prerelease:
    <<: *build_containers
    steps:
      - checkout
      - configure_build_tools
      - restore_dependency_caches
      - configure_secrets_tools
      - configure_release_tools
      - run: ./scripts/ci/steps/prerelease.sh
      - save_dependency_caches
      - notify

  release:
    <<: *build_containers
    steps:
      - checkout
      - configure_build_tools
      - restore_dependency_caches
      - configure_secrets_tools
      - configure_release_tools
      - run: ./scripts/ci/steps/release.sh
      - save_dependency_caches
      - notify

  merge_pull_request:
    <<: *build_containers
    steps:
      - checkout
      - configure_build_tools
      - configure_secrets_tools
      - run: ./scripts/ci/steps/merge-pull-request.sh
      - notify

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          <<: *only_main_and_dependabot
          <<: *slack_context
      - test:
          <<: *only_main_and_dependabot
          <<: *slack_context
          requires:
            - build
      - merge_pull_request:
          <<: *only_dependabot
          <<: *slack_context
          requires:
            - test
      - prerelease:
          <<: *only_main
          <<: *slack_context
          requires:
            - test
      - slack/on-hold:
          <<: *only_main
          <<: *slack_context
          requires:
            - prerelease
          channel: release
          template: SLACK_ON_HOLD_NOTIFICATION
      - hold:
          <<: *only_main
          type: approval
          requires:
            - prerelease
            - slack/on-hold
      - release:
          <<: *only_main
          <<: *slack_context
          requires:
            - hold
