name: Main
on:
  push:
    branches: main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        uses: ./.github/actions/asdf_install
      - name: Test
        run: ./go library:check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        uses: ./.github/actions/asdf_install
      - name: Test
        run: ./go library:test:all
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        uses: ./.github/actions/asdf_install
      - name: Test
        run: ./go library:build

  prerelease:
    runs-on: ubuntu-latest
    needs: [check, test, build]
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        uses: ./.github/actions/asdf_install
      - name: Authenticate with PyPi
        run: ./go poetry:login_to_pypi[${{ secrets.PYPI_API_KEY }}]
